Bump typescript version to ~5.5.3 (#2646)
* Bump typescript version to ~5.5.3

and run `rush update`

* bump cjs targedt to es2018 to fix the following error

>src/helpers/typeUtil.ts(7,38): error TS1503: Named capturing groups are only available when targeting 'ES2018' or later.

* undo updates in CHANGELOG

* add updates due to typescript 5.5 change